version: '3.8'

services:
  hawkes-service:
    build:
      context: ./hawkes_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: hawkes-modeling-service
